# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: HMS Zero Export
version: "1.0.0"
slug: Hoymiles Zero Export Control
description: Hoymiles Zero Export is a Python script for managing the power of the Hoymiles inverters to reduce the amount of the generated power to the grid. Based on the current power output, the script can automatically adjust the export limit of the inverter, allowing for optimal energy management.
url: "https://github.com/R0b0tter/hm-zero-export/tree/main/HoymilesZeroExport"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "NO world..."
schema:
  message: "str?"
image: "gcr.io/distroless/python3-debian12"
